# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/golang:1.12
      - image: circleci/redis:5.0
      - image: couchdb:2.3.1
    steps:
      - checkout
      - run: gotestsum
      - run:
          name: lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.18.0
            sudo cp ./bin/golangci-lint $GOPATH/bin/
            golangci-lint run -D staticcheck
