# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/golang:1.12
      - image: circleci/redis:5.0
    working_directory: /go/src/github.com/cozy/cozy-apps-registry
    steps:
      - checkout
      - run: go get -v -t ./...
      - run: gotestsum
